Repository pouncer29/ArduWatch, pull requests merged in 2020-04, with the labels that each got.

#22 Sakura 6 GPS tests
  lib/ADWatch_Functions/Watch_Compass/src/Compass_CI.cpp
  lib/ADWatch_GPS/makefile
  lib/ADWatch_GPS/src/GPSTools.h
  lib/ADWatch_GPS/src/GPSTools_CI.cpp
  lib/Mock_Libs/Adafruit_GPS_MOCK.cpp
  lib/Mock_Libs/Adafruit_GPS_MOCK.h
Labels: enhancement

#23 Sakura 1 unit tests
  CI/run_tests
  lib/ADWatch_Functions/Base_WatchFunction/src/Base_WatchFunction_CI.cpp
  lib/ADWatch_Functions/Base_WatchFunction/src/Base_WatchFunction_CI.h
  lib/ADWatch_Functions/Watch_Clock/src/Clock.cpp
  lib/ADWatch_Functions/Watch_Clock/src/Clock_CI.cpp
  lib/ADWatch_Functions/Watch_Compass/src/Compass_CI.cpp
  lib/ADWatch_Functions/Watch_Flashlight/src/Flashlight.cpp
  lib/ADWatch_Functions/Watch_Flashlight/src/Flashlight.h
  lib/ADWatch_Functions/Watch_Flashlight/src/Flashlight_CI.cpp
  lib/ADWatch_Functions/Watch_Flashlight/src/Flashlight_CI.h
  lib/ADWatch_Functions/Watch_Speedometer/src/Speedometer_CI.cpp
  lib/ADWatch_GPS/makefile
  lib/ADWatch_GPS/src/GPSTools.h
  lib/ADWatch_GPS/src/GPSTools_CI.cpp
  lib/Mock_Libs/Adafruit_GPS_MOCK.cpp
  lib/Mock_Libs/Adafruit_GPS_MOCK.h
  lib/Mock_Libs/Adafruit_NeoPixel_MOCK.cpp
  lib/Mock_Libs/Adafruit_NeoPixel_MOCK.h
Labels: enhancement

#26 Kakashi 0 build with test
  lib/ADWatch_Functions/Base_WatchFunction/Base_WatchFunction_CI.cpp
  lib/ADWatch_Functions/Base_WatchFunction/Base_WatchFunction_CI.h
  lib/ADWatch_Functions/Base_WatchFunction/makefile
  lib/ADWatch_Functions/Watch_Clock/Clock_CI.cpp
  lib/ADWatch_Functions/Watch_Clock/Clock_CI.h
  lib/ADWatch_Functions/Watch_Clock/makefile
  lib/ADWatch_Functions/Watch_Compass/Compass_CI.cpp
  lib/ADWatch_Functions/Watch_Compass/Compass_CI.h
  lib/ADWatch_Functions/Watch_Compass/makefile
  lib/ADWatch_Functions/Watch_Compass/src/Compass_Magnet.h
  lib/ADWatch_Functions/Watch_Flashlight/Flashlight_CI.cpp
  lib/ADWatch_Functions/Watch_Flashlight/Flashlight_CI.h
  lib/ADWatch_Functions/Watch_Flashlight/makefile
  lib/ADWatch_Functions/Watch_Speedometer/Speedometer_CI.cpp
  lib/ADWatch_Functions/Watch_Speedometer/Speedometer_CI.h
  lib/ADWatch_Functions/Watch_Speedometer/makefile
  lib/ADWatch_GPS/GPSTools_CI.cpp
  lib/ADWatch_GPS/GPSTools_CI.h
  lib/ADWatch_GPS/makefile
  lib/ADWatch_lib/ADWatch_CI.cpp
  lib/ADWatch_lib/ADWatch_CI.h
  lib/ADWatch_lib/makefile
Labels: CI, enhancement

#30 Hidden leaf/kakashi 0 gps integration
  InoFiles/Diagnostics/GPSTests/GPSTests.ino
  lib/ADWatch_GPS/GPSTools_CI.cpp
  lib/ADWatch_GPS/src/GPSTools.cpp
  lib/ADWatch_GPS/src/GPSTools.h
  lib/ADWatch_lib/src/ADWatch.h
  lib/Mock_Libs/TimeLib_MOCK.cpp
  lib/Mock_Libs/TimeLib_MOCK.h
Labels: CI, GPS, Tests

#31 Fixed the strobe to work with the new dial selector.
  InoFiles/Diagnostics/FunctionTests/FunctionTests.ino
  lib/ADWatch_Functions/Watch_Flashlight/src/Flashlight.cpp
  lib/ADWatch_lib/src/ADWatch.cpp
Labels: NeoPixels, Watch Function
